{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import Etudiant\n",
    "\n",
    "\n",
    "### Ajout User ###\n",
    "def add_User(self):\n",
    "    print(\"Ajout d'un utilisateur\")\n",
    "    nom = input(\"Entrez le nom: \")\n",
    "    prenom = input(\"Entrez le prénom: \")\n",
    "    num_etudiant = input(\"Entrez le numéro d'étudiant: \")\n",
    "    aScolaire = input(\"Entrez l'année d'étude: \")\n",
    "    filière = input(\"Entrez la filière: \")\n",
    "    classe = input(\"Entrez la classe: \")\n",
    "    absence = input(\"Entrez le nombre d'absences: \")\n",
    "    email = gen_email(self)\n",
    "    login = gen_login(self)\n",
    "    password = gen_password(self)\n",
    "    Etudiant = Etudiant.Etudiant(nom, prenom, num_etudiant, aScolaire, filière, classe, absence, email, login, password)\n",
    "    self.Etudiants.append(Etudiant)\n",
    "    print(\"Utilisateur ajouté\")\n",
    "    return self.Etudiants\n",
    "\n",
    "\n",
    "### Modification User ###\n",
    "def modify_User(self, Etudiant):\n",
    "    print(\"Modification de l'utilisateur\")\n",
    "    print(\"1. Nom\")\n",
    "    print(\"2. Prénom\")\n",
    "    print(\"3. Numéro d'étudiant\")\n",
    "    print(\"4. Année d'étude\")\n",
    "    print(\"5. Filière\")\n",
    "    print(\"6. Classe\")\n",
    "    print(\"7. Absences\")\n",
    "    print(\"8. Email\")\n",
    "    print(\"9. login\")\n",
    "    print(\"10. Password\")\n",
    "    print(\"11. Retour\")\n",
    "    choice = input(\"Entrez votre choix: \")\n",
    "    if choice == \"1\":\n",
    "        Etudiant.set_nom(input(\"Entrez le nouveau nom: \"))\n",
    "    elif choice == \"2\":\n",
    "        Etudiant.set_prenom(input(\"Entrez le nouveau prénom: \"))\n",
    "    elif choice == \"3\":\n",
    "        Etudiant.set_num_etudiant(input(\"Entrez le nouveau numéro d'étudiant: \"))\n",
    "    elif choice == \"4\":\n",
    "        Etudiant.set_aScolaire(input(\"Entrez la nouvelle année d'étude: \"))\n",
    "    elif choice == \"5\":\n",
    "        Etudiant.set_filière(input(\"Entrez la nouvelle filière: \"))\n",
    "    elif choice == \"6\":\n",
    "        Etudiant.set_classe(input(\"Entrez la nouvelle classe: \"))\n",
    "    elif choice == \"7\":\n",
    "        Etudiant.set_absence(input(\"Entrez le nouveau nombre d'absences: \"))\n",
    "    elif choice == \"8\":\n",
    "        Etudiant.set_email(input(\"Entrez le nouvel email: \"))\n",
    "    elif choice == \"9\":\n",
    "        Etudiant.set_login(input(\"Entrez le nouveau login: \"))\n",
    "    elif choice == \"10\":\n",
    "        Etudiant.set_password(input(\"Entrez le nouveau mot de passe: \"))\n",
    "    elif choice == \"11\":\n",
    "        modify_User(self, Etudiant)\n",
    "\n",
    "### Suppression User ###\n",
    "def delete_User(self, Etudiant):\n",
    "    print(\"Suppression de l'utilisateur\")\n",
    "    print(\"1. Oui\")\n",
    "    print(\"2. Non\")\n",
    "    choice = input(\"Entrez votre choix: \")\n",
    "    if choice == \"1\":\n",
    "        self.Etudiants.remove(Etudiant)\n",
    "        print(\"Utilisateur supprimé\")\n",
    "    elif choice == \"2\":\n",
    "        print(\"Suppression annulée\")\n",
    "    else:\n",
    "        print(\"Choix invalide\")\n",
    "        delete_User(self, Etudiant)\n",
    "    return self.Etudiants\n",
    "\n",
    "### Affichage User ###\n",
    "def afficher_User(self, Etudiant):\n",
    "    print(\"--------------------\")\n",
    "    print(\"Affichage de l'utilisateur\")\n",
    "    print(\"Nom: \", Etudiant.get_nom())\n",
    "    print(\"Prénom: \", Etudiant.get_prenom())\n",
    "    print(\"Numéro d'étudiant: \", Etudiant.get_num_etudiant())\n",
    "    print(\"Année d'étude: \", Etudiant.get_aScolaire())\n",
    "    print(\"Filière: \", Etudiant.get_filière())\n",
    "    print(\"Classe: \", Etudiant.get_classe())\n",
    "    print(\"Absences: \", Etudiant.get_absence())\n",
    "    print(\"Email: \", Etudiant.get_email())\n",
    "    print(\"Login: \", Etudiant.get_login())\n",
    "    print(\"--------------------\")\n",
    "\n",
    "\n",
    "def afficher_allUser(self):\n",
    "    print(\"--------------------\")\n",
    "    print(\"Affichage de tous les utilisateurs\")\n",
    "    for Etudiant in self.Etudiants:\n",
    "        print(\"Nom: \", Etudiant.get_nom())\n",
    "        print(\"Prénom: \", Etudiant.get_prenom())\n",
    "        print(\"Numéro d'étudiant: \", Etudiant.get_num_etudiant())\n",
    "        print(\"Année d'étude: \", Etudiant.get_aScolaire())\n",
    "        print(\"Filière: \", Etudiant.get_filière())\n",
    "        print(\"Classe: \", Etudiant.get_classe())\n",
    "        print(\"Absences: \", Etudiant.get_absence())\n",
    "        print(\"Email: \", Etudiant.get_email())\n",
    "        print(\"Login: \", Etudiant.get_login())\n",
    "        print(\"--------------------\")\n",
    "\n",
    "\n",
    "### Menu User ###\n",
    "def menu_User(self):\n",
    "    print(\"1. Ajout d'un utilisateur\")\n",
    "    print(\"2. Modification d'un utilisateur\")\n",
    "    print(\"3. Suppression d'un utilisateur\")\n",
    "    print(\"4. Affichage d'un utilisateur\")\n",
    "    print(\"5. Affichage de tous les utilisateurs\")\n",
    "    print(\"6. Retour\")\n",
    "    choice = input(\"Entrez votre choix: \")\n",
    "    if choice == \"1\":\n",
    "        add_User(self)\n",
    "    elif choice == \"2\":\n",
    "        nom = input(\"Entrez le nom de l'étudiant: \")\n",
    "        for Etudiant in self.Etudiants:\n",
    "            if Etudiant.get_num_etudiant() == num_etudiant:\n",
    "                modify_User(self, Etudiant)\n",
    "                break\n",
    "        else:\n",
    "            print(\"Utilisateur non trouvé\")\n",
    "    elif choice == \"3\":\n",
    "        nom = input(\"Entrez le nom de l'étudiant: \")\n",
    "        for Etudiant in self.Etudiants:\n",
    "            if Etudiant.get_num_etudiant() == num_etudiant:\n",
    "                delete_User(self, Etudiant)\n",
    "                break\n",
    "        else:\n",
    "            print(\"Utilisateur non trouvé\")\n",
    "    elif choice == \"4\":\n",
    "        nom = input(\"Entrez le nom de l'étudiant: \")\n",
    "        for Etudiant in self.Etudiants:\n",
    "            if Etudiant.get_num_etudiant() == num_etudiant:\n",
    "                afficher_User(self, Etudiant)\n",
    "                break\n",
    "        else:\n",
    "            print(\"Utilisateur non trouvé\")\n",
    "    elif choice == \"5\":\n",
    "        afficher_allUser(self)\n",
    "    elif choice == \"6\":\n",
    "        return\n",
    "    else:\n",
    "        print(\"Choix invalide\")\n",
    "        menu_User(self)\n",
    "    menu_User(self)\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
